# -*- coding: utf-8 -*-
countries = {
"Andorra": ["Andorra","Andorra","Andorra","Andorra"],
"Emiratos Arabes": ["Emiratos Árabes Unidos","United Arab Emirates","Vereinigte Arabische Emirate","Unió dels Emirats Àrabs"],
"Afganistán": ["Afganistán","Afghanistan","Afghanistan","Afganistan"],
"Antigua & Barbuda": ["Antigua y Barbuda","Antigua and Barbuda","Antigua und Barbuda","Antigua i Barbuda"],
"Anguilla": ["Anguila","Anguilla","Anguilla","Anguilla"],
"Albania": ["Albania","Albania","Albanien","Albània"],
"Armenia": ["Armenia","Armenia","Armenien","Armènia"],
"Antillas holandesas": ["Antillas Neerlandesas","Netherlands Antilles","Niederländische Antillen","Antilles Holandeses"],
"Angola": ["Angola","Angola","Angola","Angola"],
"Argentina": ["Argentina","Argentina","Argentinien","Argentina"],
"Austria": ["Austria","Austria","Österreich","Àustria"],
"Australia": ["Australia","Australia","Australien","Austràlia"],
"Aruba": ["Aruba","Aruba","Aruba","Aruba"],
"Azerbaiján": ["Azerbaiyán","Azerbaijan","Aserbaidschan","Azerbaitjan"],
"Bosnia Herzegovina": ["Bosnia y Hercegovina","Bosnia and Herzegovina","Bosnien und Herzegowina","Bòsnia i Hercegovina"],
"Barbados": ["Barbados","Barbados","Barbados","Barbados"],
"Bangla Desh": ["Bangladesh","Bangladesh","Bangladesch","Bangla Desh"],
"Bhután": ["Bután","Bhutan","Bhutan","Bhutan"],
"Bélgica": ["Bélgica","Belgium","Belgien","Bèlgica"],
"Burkina Faso": ["Burkina Faso","Burkina Faso","Burkina Faso","Burkina Faso"],
"Bulgaria": ["Bulgaria","Bulgaria","Bulgarien","Bulgària"],
"Bahrain": ["Bahráin","Bahrain","Bahrain","Bahrain"],
"Burundi": ["Burundi","Burundi","Burundi","Burundi"],
"Benin": ["Benín","Benin","Benin","Benín"],
"Bermudas": ["Bermudas","Bermuda","die Bermudas","Bermuda"],
"Brunei": ["Brunéi","Brunei","Brunei Darussalam","Brunei"],
"Bolivia": ["Bolivia","Bolivia","Bolivien","Bolívia"],
"Brasil": ["Brasil","Brazil","Brasilien","Brasil"],
"Bahamas": ["Bahamas","The Bahamas","Bahamas","Bahames"],
"Botswana": ["Botsuana","Botswana","Botsuana","Botswana"],
"Bielorrusia": ["Bielorrusia","Belarus","Belarus","Bielorússia"],
"Belice": ["Belice","Belize","Belize","Belize"],
"Canadá": ["Canadá","Canada","Kanada","Canadà"],
"Congo (Kinshasa)": ["República Democrática del Congo","Democratic Republic of the Congo","Demokratische Republik Kongo","Congo, República Democràtica del"],
"República Centroafricana": ["República Centroafricana","Central African Republic","Zentralafrikanische Republik","República Centreafricana"],
"Congo (Brazzaville)": ["Congo","Congo","Kongo","Congo"],
"Suiza": ["Suiza","Switzerland","Schweiz","Suïssa"],
"Costa de Marfil": ["Costa de Marfil","Côte d'Ivoire","Côte d'Ivoire","Costa d'Ivori"],
"Islas Cook": ["Islas Cook","Cook Islands","Cookinseln","Illes Cook"],
"Chile": ["Chile","Chile","Chile","Xile"],
"Camerún": ["Camerún","Cameroon","Kamerun","Camerun"],
"China": ["China","China","China","Xina"],
"Colombia": ["Colombia","Colombia","Kolumbien","Colòmbia"],
"Costa Rica": ["Costa Rica","Costa Rica","Costa Rica","Costa Rica"],
"Serbia & Montenegro": ["Serbia & Montenegro","Serbia & Montenegro","Serbien und Montenegro","Sèrbia i Montenegro"],
"Cuba": ["Cuba","Cuba","Kuba","Cuba"],
"Cabo Verde": ["Cabo Verde","Cape Verde","Kap Verde","Cap Verd"],
"Chipre": ["Chipre","Cyprus","Zypern","Xipre"],
"República Checa": ["República Checa","Czech Republic","Tschechische Republik","República Txeca"],
"Alemania": ["Alemania","Germany","Deutschland","Alemanya"],
"Djibouti": ["Yibuti","Djibouti","Dschibuti","Djibouti"],
"Dinamarca": ["Dinamarca","Denmark","Dänemark","Dinamarca"],
"Dominica": ["Dominica","Dominica","Dominica","Dominica"],
"República Dominicana": ["República Dominicana","Dominican Republic","Dominikanische Republik","República Dominicana"],
"Argelia": ["Argelia","Algeria","Algerien","Algèria"],
"Ecuador": ["Ecuador","Ecuador","Ecuador","Equador"],
"Estonia": ["Estonia","Estonia","Estland","Estònia"],
"Egipto": ["Egipto","Egypt","Ägypten","Egipte"],
"Sahara": ["Sáhara Occidental","Western Sahara","Westsahara","Sàhara Occidental"],
"Eritrea": ["Eritrea","Eritrea","Eritrea","Eritrea"],
"España": ["España","Spain","Spanien","Espanya"],
"Etiopía": ["Etiopía","Ethiopia","Äthiopien","Etiòpia"],
"Finlandia": ["Finlandia","Finland","Finnland","Finlàndia"],
"Fiji": ["Fiyi","Fiji","Fidschi","Fiji"],
"Islas Malvinas": ["Islas Malvinas","Falkland Islands","Falklandinseln","Illes Malvines (Falkland)"],
"Micronesia": ["Micronesia","Micronesia","Mikronesien","Micronèsia, Estats Federats de"],
"Islas Faroe": ["Islas Feroe","Faeroe Islands","Färöer","Illes Fèroe"],
"Francia": ["Francia","France","Frankreich","França"],
"Gabón": ["Gabón","Gabon","Gabun","Gabon"],
"Gran Bretaña": ["Reino Unido","United Kingdom","Vereinigtes Königreich","Regne Unit"],
"Granada": ["Granada","Grenada","Grenada","Grenada"],
"Georgia": ["Georgia","Georgia","Georgien","Geòrgia"],
"Guayana Fr.": ["Guayana Francesa","French Guiana","Französisch-Guayana","Guaiana Francesa"],
"Ghana": ["Ghana","Ghana","Ghana","Ghana"],
"Gibraltar": ["Gibraltar","Gibraltar","Gibraltar","Gibraltar"],
"Groenlandia": ["Groenlandia","Greenland","Grönland","Groenlàndia"],
"Gambia": ["Gambia","The Gambia","Gambia","Gàmbia"],
"Guinea": ["Guinea","Guinea","Guinea","Guinea"],
"Guadalupe": ["Guadalupe","Guadeloupe","Guadeloupe","Guadalupe"],
"Guinea ecuatorial": ["Guinea Ecuatorial","Equatorial Guinea","Äquatorialguinea","Guinea Equatorial"],
"Grecia": ["Grecia","Greece","Griechenland","Grècia"],
"Guatemala": ["Guatemala","Guatemala","Guatemala","Guatemala"],
"Guinea-Bissau": ["Guinea-Bissau","Guinea-Bissau","Guinea-Bissau","Guinea Bissau"],
"Guyana": ["Guyana","Guyana","Guyana","Guyana"],
"Hong Kong": ["Hong Kong","Hong Kong","Hongkong","Hong Kong"],
"Honduras": ["Honduras","Honduras","Honduras","Hondures"],
"Croacia": ["Croacia","Croatia","Kroatien","Croàcia"],
"Haití": ["Haití","Haiti","Haiti","Haití"],
"Hungría": ["Hungría","Hungary","Ungarn","Hongria"],
"Indonesia": ["Indonesia","Indonesia","Indonesien","Indonèsia"],
"Irlanda": ["Irlanda","Ireland","Irland","Irlanda"],
"Israel": ["Israel","Israel","Israel","Israel"],
"India": ["India (la)","India","Indien","Índia"],
"Irak": ["Iraq","Iraq","Irak","Iraq"],
"Irán": ["Irán","Iran","Iran","Iran"],
"Islandia": ["Islandia","Iceland","Island","Islàndia"],
"Italia": ["Italia","Italy","Italien","Itàlia"],
"Jamaica": ["Jamaica","Jamaica","Jamaika","Jamaica"],
"Jordania": ["Jordania","Jordan","Jordanien","Jordània"],
"Japón": ["Japón","Japan","Japan","Japó"],
"Kenya": ["Kenia","Kenya","Kenia","Kenya"],
"Kirguizistán": ["Kirguizistán","Kyrgyzstan","Kirgisistan","Kirguizistan"],
"Camboya": ["Camboya","Cambodia","Kambodscha","Cambodja"],
"Kiribati": ["Kiribati","Kiribati","Kiribati","Kiribati"],
"Comoros": ["Comoras","Comoros","Komoren","Comores"],
"Saint Kitts & Nevis": ["San Cristóbal y Nieves","Saint Kitts and Nevis","St. Kitts und Nevis","Saint Christopher i Nevis"],
"Corea del Norte": ["Corea del Norte","North Korea","Demokratische Volksrepublik Korea","Corea del Nord"],
"Corea del Sur": ["Corea del Sur","South Korea","Republik Korea","Corea del Sud"],
"Kuwait": ["Kuwait","Kuwait","Kuwait","Kuwait"],
"Islas Caimán": ["Islas Caimán","Cayman Islands","Kaimaninseln","Illes Caiman"],
"Kazajstán": ["Kazajistán","Kazakhstan","Kasachstan","Kazakhstan"],
"Laos": ["Laos","Laos","Laos","Laos"],
"Líbano": ["Líbano","Lebanon","Libanon","Líban"],
"Santa Lucia": ["Santa Lucía","Saint Lucia","St. Lucia","Saint Lucia"],
"Liechtenstein": ["Liechtenstein","Liechtenstein","Liechtenstein","Liechtenstein"],
"Sri Lanka": ["Sri Lanka","Sri Lanka","Sri Lanka","Sri Lanka"],
"Liberia": ["Liberia","Liberia","Liberia","Libèria"],
"Lesotho": ["Lesoto","Lesotho","Lesotho","Lesotho"],
"Lituania": ["Lituania","Lithuania","Litauen","Lituània"],
"Luxemburgo": ["Luxemburgo","Luxembourg ","Luxemburg","Luxemburg"],
"Letonia": ["Letonia","Latvia","Lettland","Letònia"],
"Libia": ["Libia","Libya","Libyen","Líbia"],
"Marruecos": ["Marruecos","Morocco","Marokko","Marroc"],
"Monaco": ["Mónaco","Monaco","Monaco","Mònaco"],
"Moldavia": ["Moldavia","Moldova","Republik Moldau","Moldàvia"],
"Madagascar": ["Madagascar","Madagascar","Madagaskar","Madagascar"],
"Islas Marshall": ["Islas Marshall","Marshall Islands","Marshallinseln","Illes Marshall"],
"Macedonia": ["Macedonia","Republic of Macedonia","Republik Mazedonien","Macedònia"],
"Mali": ["Malí","Mali","Mali","Mali"],
"Myanmar (Birmania)": ["Birmania; Myanmar","Myanmar","Myanmar","Myanmar"],
"Mongolia": ["Mongolia","Mongolia","Mongolei","Mongòlia"],
"Martinique": ["Martinica","Martinique","Martinique","Martinica"],
"Mauritania": ["Mauritania","Mauritania","Mauretanien","Mauritània"],
"Montserrat": ["Montserrat","Montserrat","Montserrat","Montserrat"],
"Malta": ["Malta","Malta","Malta","Malta"],
"Mauricio": ["Mauricio","Mauritius","Mauritius","Maurici"],
"Maldivas": ["Maldivas","Maldives","Malediven","Maldives"],
"Malawi": ["Malaui","Malawi","Malawi","Malawi"],
"México": ["México","Mexico","Mexiko","Mèxic"],
"Malasia": ["Malasia","Malaysia","Malaysia","Malàisia"],
"Mozambique": ["Mozambique","Mozambique","Mosambik","Moçambic|"],
"Namibia": ["Namibia","Namibia","Namibia","Namíbia"],
"Nueva Caledonia": ["Nueva Caledonia","New Caledonia","Neukaledonien","Nova Caledònia"],
"Níger": ["Níger","Niger","Niger","Níger"],
"Islas Norfolk": ["Isla Norfolk","Norfolk Island","Norfolkinsel","Illa Norfolk"],
"Nigeria": ["Nigeria","Nigeria","Nigeria","Nigèria"],
"Nicaragua": ["Nicaragua","Nicaragua","Nicaragua","Nicaragua"],
"Países Bajos": ["Países Bajos","Netherlands","Niederlande","Països Baixos"],
"Noruega": ["Noruega","Norway","Norwegen","Noruega"],
"Nepal": ["Nepal","Nepal","Nepal","Nepal"],
"Nauru": ["Nauru","Nauru","Nauru","Nauru"],
"Niue": ["Niue","Niue","Niue","Niue"],
"Nueva Zelanda": ["Nueva Zelanda","New Zealand","Neuseeland","Nova Zelanda"],
"Omán": ["Omán","Oman","Oman","Oman"],
"Panamá": ["Panamá","Panama","Panama","Panamà"],
"Perú": ["Perú","Peru","Peru","Perú"],
"Polinesia": ["Polinesia Francesa","French Polynesia","Französisch-Polynesien","Polinèsia Francesa"],
"Papua Nueva Guinea": ["Papúa-Nueva Guinea","Papua New Guinea","Papua-Neuguinea","Papua Nova Guinea"],
"Filipinas": ["Filipinas","Philippines","Philippinen","Filipines"],
"Pakistán": ["Pakistán","Pakistan","Pakistan","Pakistan"],
"Polonia": ["Polonia","Poland","Polen","Polònia"],
"San Pierre & Miquelon": ["San Pedro y Miquelón","Saint Pierre and Miquelon","St. Pierre und Miquelon","Saint Pierre i Miquelon"],
"Palestina": ["Palestina","Palestine","Palestine","Palestina"],
"Portugal": ["Portugal","Portugal","Portugal","Portugal"],
"Palau": ["Palaos","Palau","Palau","Palau"],
"Paraguay": ["Paraguay","Paraguay","Paraguay","Paraguai"],
"Qatar": ["Qatar","Qatar","Katar","Qatar"],
"Reunión": ["Reunión","Reunion","Reunion","Reunion"],
"Rumanía": ["Rumanía","Romania","Rumänien","Romania"],
"Rusia": ["Rusia","Russia","Russische Föderation","Rússia"],
"Ruanda": ["Ruanda","Rwanda","Ruanda","Rwanda"],
"Arabia Saudita": ["Arabia Saudí","Saudi Arabia","Saudi-Arabien","Aràbia Saudita"],
"Islas Salomón": ["Islas Salomón","Solomon Islands","Salomonen","Illes Salomó"],
"Seychelles": ["Seychelles","Seychelles","Seychellen","Seychelles"],
"Sudán": ["Sudán","Sudan","Sudan","Sudan"],
"Suecia": ["Suecia","Sweden","Schweden","Suècia"],
"Singapur": ["Singapur","Singapore","Singapur","Singapur"],
"Santa Helena": ["Santa Helena","Saint Helena","St. Helena","Saint Helena"],
"Eslovenia": ["Eslovenia","Slovenia","Slowenien","Eslovènia"],
"Eslovaquia": ["Eslovaquia","Slovakia","Slowakei","Eslovàquia"],
"Sierra Leona": ["Sierra Leona","Sierra Leone","Sierra Leone","Sierra Leone"],
"San Marino": ["San Marino","San Marino","San Marino","San Marino"],
"Senegal": ["Senegal","Senegal","Senegal","Senegal"],
"Somalia": ["Somalia","Somalia","Somalia","Somàlia"],
"Suriname": ["Surinam","Suriname","Suriname","Surinam"],
"Santo Tomé & Príncipe": ["Santo Tomé y Príncipe","São Tomé and Príncipe","São Tomé und Príncipe","Sao Tomé i Príncipe"],
"El Salvador": ["El Salvador","El Salvador","El Salvador","El Salvador"],
"Siria": ["Siria","Syria","Syrien","Síria"],
"Swazilandia": ["Suazilandia","Swaziland","Swasiland","Swazilàndia"],
"Turcos & Caicos": ["Islas Turcas y Caicos","Turks and Caicos Islands","Turks- und Caicosinseln","Illes Turks i Caicos"],
"Chad": ["Chad","Chad","Tschad","Txad"],
"French Southern Lands": ["Territorios Australes Franceses","French Southern Territories","Französische Gebiete (Ind. Oz.)","Territoris Francesos del Sud"],
"Togo": ["Togo","Togo","Togo","Togo"],
"Tailandia": ["Tailandia","Thailand","Thailand","Tailàndia"],
"Tadschikistan": ["Tayikistán","Tajikistan","Tadschikistan","Tadjikistan"],
"Tokelau": ["Tokelau","Tokelau","Tokelau","Tokelau"],
"Timor oriental": ["Timor Oriental","East Timor","Osttimor","Timor-Leste"],
"Turkmenistan": ["Turkmenistán","Turkmenistan","Turkmenistan","Turkmenistan"],
"Túnez": ["Túnez","Tunisia","Tunesien","Tunísia"],
"Tonga": ["Tonga","Tonga","Tonga","Tonga"],
"Turquía": ["Turquía","Turkey","Türkei","Turquia"],
"Trinidad & Tabago": ["Trinidad y Tobago","Trinidad and Tobago","Trinidad und Tobago","Trinitat i Tobago"],
"Tuvalu": ["Tuvalu","Tuvalu","Tuvalu","Tuvalu"],
"Taiwán": ["Taiwán","Taiwan","Taiwan","Taiwan"],
"Tanzania": ["Tanzania","Tanzania","Tansania","Tanzània"],
"Ucrania": ["Ucrania","Ukraine","Ukraine","Ucraïna"],
"Uganda": ["Uganda","Uganda","Uganda","Uganda"],
"Uruguay": ["Uruguay","Uruguay","Uruguay","Uruguai"],
"Uzbekistan": ["Uzbekistán","Uzbekistan","Usbekistan","Uzbekistan"],
"Vaticano": ["El Vaticano","Vatican City","Vatikanstadt","Ciutat del Vaticà"],
"San Vincente & Granadinas": ["San Vicente y las Granadinas","Saint Vincent and the Grenadines","St. Vincent und die Grenadinen","Saint Vincent i les Grenadines"],
"Venezuela": ["Venezuela","Venezuela","Venezuela","Veneçuela"],
"Is. Vírgenes": ["Islas Vírgenes Británicas","British Virgin Islands","Britische Jungferninseln","Illes Verge Britàniques"],
"Vietnam": ["Vietnam","Vietnam","Vietnam","Vietnam"],
"Vanuatu": ["Vanuatu","Vanuatu","Vanuatu","Vanuatu"],
"Wallis & Futuna": ["Wallis y Futuna","Wallis and Futuna","Wallis und Futuna","Wallis i Futuna"],
"Samoa-oeste": ["Samoa","Samoa","Samoa","Samoa"],
"Yemen": ["Yemen","Yemen","Jemen","Iemen"],
"Mayotte": ["Mayotte","Mayotte","Mayotte","Mayotte"],
"Sudáfrica": ["Sudáfrica","South Africa","Südafrika","Sud-àfrica"],
"Zambia": ["Zambia","Zambia","Sambia","Zàmbia"],
"Zimbabwe": ["Zimbabue","Zimbabwe","Simbabwe","Zimbabwe"] }

cata_reg = {
        "España": "Espanya", 
        "Baleares": "Illes Balears",
        "La Rioja": "La Rioja",   
        "Madrid": "Comunitat de Madrid",
        "Murcia": "Regió de Múrcia",
        "Navarra": "Navarra",
        "Asturias": "Principat d'Astúries",
        "Cantabria": "Cantàbria",
        "Andalucía": "Andalusia",
        "Aragón": "Aragó",
        "Canarias": "Illes Canàries",
        "Castilla-La Mancha": "Castella - la Manxa",
        "Castilla y León": "Castella i Lleó",
        "Cataluña": "Catalunya",
        "Extremadura": "Extremadura",
        "Galicia": "Galícia",
        "Pais Vasco": "País Basc",
        "Valencia": "País Valencià" }

def install(lang):
    global countries
    langs = { 'es': 0, 'en': 1, 'de': 2, 'ca': 3 }
    l = langs[lang]
    temp = {}
    for k in list(countries.keys()):
        temp[k] = countries[k][l]
    countries = temp
    countries['USA'] = 'USA'
    import builtins
    builtins.__dict__['t'] = trad


def trad(name):
    try:
        return countries[name]
    except KeyError:
        return name
